name: release

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v3
      - name: Log in to Github container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io/${{ github.repository }}
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}
      - name: Build and push the blog
        id: push
        uses: docker/build-push-action@v5
        with:
          push: true
          context: .
          tags: ghcr.io/${{github.repository}}:latest,ghcr.io/${{github.repository}}:${{github.ref_name}},ghcr.io/${{github.repository}}:${{github.sha}}
          file: Dockerfile
          platforms: linux/amd64
